### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by haseebnqureshi** [haseebnqureshi/serverless-hq#24]
- [x] Remove pre-populated command prompt answers from bin index.js
- [x] Update our README for new rewrite
- [x] NPM publish new release
- [x] Post in hacker news, SLS gitter, message AC360
