### ISSUE TITLE
Development checklist

### ISSUE THREAD

**Issue by haseebnqureshi** [haseebnqureshi/serverless-hq#25]
- [ ] Upgrade to SLS 1.5.0
- [ ] Create Cognito pool, ideally by CloudFormation template, but can do by JS if needed
- [ ] Grab Cognito pool ARN
- [ ] Add Cognito pool ARN to Lambda handlers
- [ ] Test
